# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Research Software Collaborations in Physics
email: Peter.Elmer@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  The HSF-India network of networks extends the growing research software collaborations between physics and computer science researchers in the U.S. and Europe to include researchers in India. This network-of-networks will build expertise and drive research software collaborations in areas which are critical to advance particle, nuclear and astroparticle physics research: novel approaches to analysis systems, next-generation simulation tools and methods for open science. It will connect software experts and researchers across the international community in a collaborative framework that promotes software collaborations. Immediate mutual benefits of the international collaboration will be a training network that enables early-career researchers to pursue impactful research software initiatives in ways that advance their careers in experimental data-intensive science.  HSF-India will build international collaborative structures which will enable innovation in critical software areas for discovery in particle, nuclear and astroparticle physics and lay the foundations for similar international collaborations across the scientific spectrum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://research-software-collaborations.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: tbd_hep
github_username: research-software-collaborations
excerpt_separator: <!--more-->
logo: /assets/logos/Iris-hep-5-just-graphic.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/logos/Iris-hep-5-just-graphic.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

strict_front_matter: true

liquid:
  error_mode: strict
  strict_filters: true

# Exclude from processing.
exclude:
  - _cache
  - _scripts
  - bin
  - .github
  - Rakefile

sass:
  sass_dir: _sass

inspire:
  cache-dir: _cache
  pub-dir: publications
  authors:
    min-len: 10
    trunc-len: 1
  open-science-categories:
    - algo
    - general
    - physics

indico:
  url: https://indico.cern.ch
  cache-command: bundle exec rake cache
  timeout: 240 # topical is getting close to 60 seconds, the default
  paginate: 25
  ids:
    topical: 15964
    events: 15896

collections:
  institutes:
    output: true
    permalink: /:collection/:name
  networks:
    output: true
    permalink: /:collection/:name
  collaborators:
    output: true
    permalink: /:collection/:name


iris-hep:
  extra-focus-areas:
    - core
    - outreach
  projectless-focus-areas:
    - core
    - ssc
    - blueprint
    - ssl
